package com.mygdx.game.client.json;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Net;
import com.badlogic.gdx.net.HttpStatus;
import com.badlogic.gdx.Net.HttpResponseListener;
import com.mygdx.game.client.json.exceptions.JsonClientException;
import com.mygdx.game.hex.Board;

public class JsonClient {
	
	private String baseURL = "http://localhost:9000";
	public static final String POST = "POST";
	
	private static JsonClient instance;
    private JsonClient() {
    }
    public static synchronized JsonClient getInstance() {
        if(instance == null) {
            instance = new JsonClient();
        }
        return instance;
    }
    
	public <T> void sendPost(Object requestObject, String uri, final ResponseCallback<T> callback, final Class<T> clazz) {
        sendRequest(requestObject, uri, POST, callback, clazz);
    }
	
	 private <T> void sendRequest(Object requestObject, String uri, String method, final ResponseCallback<T> callback, final Class<T> clazz) {

	        String requestJson = JsonUtil.getInstance().toJson(requestObject);

	        Net.HttpRequest request = new Net.HttpRequest(method);
	        final String url = getURL(uri);
	        request.setUrl(url);

	        request.setContent(requestJson);

	        request.setHeader("Content-Type", "application/json");
	        request.setHeader("Accept", "application/json");

	        Gdx.net.sendHttpRequest(request, new Net.HttpResponseListener() {
	            public void handleHttpResponse(Net.HttpResponse httpResponse) {
	                int statusCode = httpResponse.getStatus().getStatusCode();
	                if(statusCode != HttpStatus.SC_OK) {
	                	callback.onFail(new JsonClientException(url,"Received http status: " + statusCode));
	                    return;
	                }

	                String responseJson = httpResponse.getResultAsString();
	                try {
	                    T responseObject = JsonUtil.getInstance().fromJson(clazz, responseJson);
	                    callback.onResponse(responseObject);
	                }
	                catch(Exception exception) {
	                    callback.onFail(new JsonClientException(url, "Exception parsing response as JSON.", exception));
	                }
	            }

	            public void failed(Throwable t) {
	                callback.onFail(new JsonClientException(url, t));
	            }

				@Override
				public void cancelled() {
					// TODO Auto-generated method stub
					
				}
	        });
	        

	    }
	 	
	 /**
	  * this method is specifically for testing purposes for loading a board from the database. 
	  * 	this is not a good design, just a proof
	  * 
	  * I wrote this method just to handle the specific case of creating a board, 
	  * 	because we need to get a board object to the HttpResponseListener
	  * 	this is necessary because the board has to be given a reference to 
	  * 	the Tile data structure generated by the responseListener (var: listen) of this web request
	  * @param board
	  * @param uri
	  */
	 	public void mySendRequest(Board board, String uri) {
	 		
	 		String requestJson = JsonUtil.getInstance().toJson("");
	        Net.HttpRequest request = new Net.HttpRequest(POST);
	        final String url = getURL(uri);
	        request.setUrl(url);

	        request.setContent(requestJson);
	        request.setHeader("Content-Type", "application/json");
	        request.setHeader("Accept", "application/json");
	        HttpResponseListener listen = new BoardResponseListener(board);    
			
	        //creates a new thread, returns control right this this class.
	        //NOTE: I noticed that this thread gets destroyed after the responseListener calls handleHttpResponse()
	        Gdx.net.sendHttpRequest(request,listen);
	 	}
	        
			
	    private String getURL(String uri) {
	        return baseURL + uri;
	    }

}
